import os

ELEVE_ROLE_NAME = "Elève"
PROF_ROLE_NAME = "Professeur"
ADMIN_ROLE_NAME = "Admin"
ASKING_ROLE_NAME = "Asking"
TALKING_ROLE_NAME = "Talking"

ALLOWED_ROLES = [PROF_ROLE_NAME]
ALLOWED_CHANNELS = ["général"]

GUILD_NAME = "test server"
SECURED_VOCAL_SERVER_NAMES = ["Général"]

BOT_TOKEN = os.environ["DISCORD_BOT_TOKEN"]