import os

ELEVE_ROLE_NAME = "Elève"
PROF_ROLE_NAME = "Professeur"
ADMIN_ROLE_NAME = "Admin"
ASKING_ROLE_NAME = "Asking"
TALKING_ROLE_NAME = "Talking"

ALLOWED_ROLES = [PROF_ROLE_NAME]
ALLOWED_CHANNELS = ["cours"]

GUILD_NAME = "Première 1"
SECURED_VOCAL_SERVER_NAMES = ["Classe"]

BOT_TOKEN = os.environ["DISCORD_BOT_TOKEN"]
